source 'https://rubygems.org'

gem 'cucumber'
gem 'rspec'
gem 'rake'
gem 'site_prism'
gem 'pry'
gem 'site_prism'
gem 'selenium-webdriver'
gem 'faker'
gem 'guard'
gem 'guard-minitest'
gem 'guard-rspec'